set_property PACKAGE_PIN W5 [get_ports Clock]
set_property IOSTANDARD LVCMOS33 [get_ports Clock]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports Clock]
set_property PACKAGE_PIN V17 [get_ports {T}]
set_property IOSTANDARD LVCMOS33 [get_ports {T}]
set_property PACKAGE_PIN U16 [get_ports {Q}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q}]